### PR TITLE
Updates to de-localize paths.

### PR DESCRIPTION
**Pull request by dansajner**
These changes are needed for mkvm.rb to run from gem installation.

### CODE REVIEW

**Comment by nchowning** [comment]
Looks good to me!

**Comment by adamcstephens** [comment]
Seems logical. :shipit:

**Comment by skpy** [comment]
Looks okay!  I don't know if anyone would ever have any problems with the hard-coded `/tmp/mkvm` workdir, though.  If that could use the user's home directory, it would ensure that multiple people could use this gem simultaneously on a shared server.

**Comment by dansajner** [comment]
@skpy I didn't love the hardcoded `/tmp/mkvm` either so I updated `work_dir` to be relative to your session.

**Comment by adamcstephens** [comment]
I like it being relative my session even less. mkvm directories will get put wherever...

Ruby has a mktmpdir function, could we use that instead?

http://ruby-doc.org/stdlib-1.9.3/libdoc/tmpdir/rdoc/Dir.html#method-c-mktmpdir

**Comment by dansajner** [comment]
We need to stop thinking about building VMs from the command line.  This is all going to be wrapped up in jobs that have transient workspaces.  In the event that someone must run mkvm.rb manually then, yes, they'll have a directory left over.

**Pull request merged**
